version: '3.8'

services:
  web:
    build: .
    container_name: gestion_integral_app
    restart: always
    ports:
      - "8087:8000"
    volumes:
      # Volumes pour ne pas perdre la base SQLite et les fichiers téléchargés (media)
      - .:/app
      - django_static:/app/staticfiles
      - django_media:/app/media
    environment:
      - DEBUG=True  # À passer à False en production dans vos settings

volumes:
  django_media: