# Generated by Django 5.2.13 on 2026-05-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('login_failed', 'Tentative de connexion échouée'), ('password_change', 'Changement de mot de passe'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('export', 'Export'), ('import', 'Import'), ('activate', 'Activation'), ('pause', 'Mise en pause'), ('close', 'Clôture'), ('validate', 'Validation'), ('etat_change', "Changement d'état"), ('role_change', 'Changement de rôle'), ('photo_add', 'Photo ajoutée'), ('map_click', 'Clic carte')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('auth', 'Authentification'), ('inventory', 'Inventaire'), ('campaigns', 'Campagnes'), ('clients', 'Clients'), ('users', 'Utilisateurs'), ('planning', 'Planning'), ('map', 'Carte'), ('reports', 'Rapports')], default='inventory', max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='accounts_au_user_id_7b1069_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='accounts_au_action_c683b9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module', 'created_at'], name='accounts_au_module_0c9200_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['level'], name='accounts_au_level_f52852_idx'),
        ),
    ]
