# Generated by Django 5.2.13 on 2026-05-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog_changes_auditlog_level_auditlog_object_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('login_failed', 'Tentative de connexion échouée'), ('password_change', 'Changement de mot de passe'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('export', 'Export'), ('import', 'Import'), ('activate', 'Activation'), ('pause', 'Mise en pause'), ('close', 'Clôture'), ('validate', 'Validation'), ('etat_change', "Changement d'état"), ('role_change', 'Changement de rôle'), ('add', 'Ajout'), ('map_click', 'Clic carte')], max_length=20),
        ),
    ]
