# Generated by Django 5.2.13 on 2026-04-23 11:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDiffusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duree_sec', models.PositiveIntegerField(default=10)),
                ('genere_auto', models.BooleanField(default=True)),
                ('campagne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campagne')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.client')),
                ('ecran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.ecrannumerique')),
                ('ligne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='campaigns.lignecampagne')),
            ],
            options={
                'verbose_name': 'Log de Diffusion',
                'verbose_name_plural': 'Main Courante',
                'ordering': ['timestamp'],
            },
        ),
    ]
