# Generated by Django 5.2.15 on 2026-09-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logdiffusion',
            options={'ordering': ['timestamp'], 'verbose_name': 'Log de Diffusion', 'verbose_name_plural': 'Journaux de diffusion'},
        ),
    ]
