# Generated by Django 5.2.13 on 2026-04-23 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code interne')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom / Libellé')),
                ('type_support', models.CharField(choices=[('panneau', 'Panneau Statique'), ('ecran', 'Écran Numérique')], max_length=10, verbose_name='Type')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('ville', models.CharField(blank=True, default='Ouagadougou', max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('etat', models.CharField(choices=[('bon', 'Bon état'), ('maintenance', 'En maintenance'), ('panne', 'En panne')], default='bon', max_length=20)),
                ('date_installation', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('photo_principale', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Photo principale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Publicitaire',
                'verbose_name_plural': 'Supports Publicitaires',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PhotoMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='proofs/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('etat_apres', models.CharField(blank=True, choices=[('bon', 'Bon état'), ('maintenance', 'En maintenance'), ('panne', 'En panne')], max_length=20)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_maintenance', to='inventory.support')),
            ],
            options={
                'verbose_name': 'Photo de Maintenance',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EcranNumerique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ecran', models.CharField(choices=[('interieur', 'Intérieur'), ('exterieur', 'Extérieur'), ('mobilier', 'Mobilier Urbain')], default='exterieur', max_length=20, verbose_name="Type d'affichage")),
                ('resolution', models.CharField(choices=[('hd', 'HD 1280×720'), ('fullhd', 'Full HD 1920×1080'), ('4k', '4K 3840×2160')], default='fullhd', max_length=10)),
                ('taille_pouces', models.PositiveIntegerField(default=55, help_text='Diagonale en pouces')),
                ('heure_allumage', models.TimeField(default='06:00:00', help_text="Heure à laquelle l'écran s'allume")),
                ('heure_extinction', models.TimeField(default='23:00:00', help_text="Heure à laquelle l'écran s'éteint")),
                ('support', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecran_info', to='inventory.support')),
            ],
            options={
                'verbose_name': 'Configuration Écran',
                'verbose_name_plural': 'Configurations Écrans',
            },
        ),
        migrations.CreateModel(
            name='FacePanneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('A', 'Face A'), ('B', 'Face B')], default='A', max_length=1)),
                ('format', models.CharField(choices=[('4x3', '4m × 3m'), ('8x3', '8m × 3m'), ('12x4', '12m × 4m'), ('mupi', 'Mupi'), ('custom', 'Personnalisé')], default='4x3', max_length=10)),
                ('eclairage', models.CharField(choices=[('non', 'Non éclairé'), ('backlit', 'Rétroéclairé'), ('frontlit', 'Éclairage avant'), ('led', 'LED')], default='non', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='inventory.support')),
            ],
            options={
                'verbose_name': 'Face de Panneau',
                'verbose_name_plural': 'Faces de Panneau',
                'ordering': ['label'],
                'unique_together': {('support', 'label')},
            },
        ),
    ]
