# Generated by Django 5.2.13 on 2026-04-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecrannumerique',
            name='taille_pouces',
        ),
        migrations.AddField(
            model_name='ecrannumerique',
            name='cellule',
            field=models.CharField(choices=[('8x5', '40'), ('6x4', '24'), ('5x4', '20'), ('4x3', '12')], default='6x4', help_text='Nombre de spots simultanés (ex: 6x4 = 24)', max_length=10),
        ),
        migrations.AlterField(
            model_name='facepanneau',
            name='format',
            field=models.CharField(choices=[('12m2', '4m × 3m'), ('20m2', '4m × 5m'), ('21m2', '7m × 3m'), ('96m2', '24m × 4m'), ('60m2', '12m × 5m'), ('48m2', '12m × 4m'), ('45m2', '9m × 5m'), ('40m2', '10m × 4m'), ('1,20x1,80', '1,20m × 1,80m'), ('36m2', '12m × 3m'), ('16m2', '4m × 4m'), ('20m2', '5m × 4m'), ('12m2', '4m × 3m'), ('8m2', '8m × 3m'), ('12m2', '12m × 4m'), ('mupi', 'Mupi'), ('custom', 'Personnalisé')], default='4x3', max_length=10),
        ),
    ]
