# Generated by Django 5.2.13 on 2026-04-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_ecrannumerique_taille_pouces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facepanneau',
            name='format',
            field=models.CharField(choices=[('4m × 3m', '12m2'), ('4m × 5m', '20m2'), ('7m × 3m', '21m2'), ('24m × 4m', '96m2'), ('12m × 5m', '60m2'), ('12m × 4m', '48m2'), ('9m × 5m', '45m2'), ('10m × 4m', '40m2'), ('1,20m × 1,80m', '2,16m2'), ('12m × 3m', '36m2'), ('4m × 4m', '16m2'), ('5m × 4m', '20m2'), ('4m × 3m', '12m2'), ('mupi', 'Mupi'), ('custom', 'Personnalisé')], default='4m × 3m', max_length=20),
        ),
    ]
