# Generated by Django 5.2.13 on 2026-04-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_facepanneau_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facepanneau',
            name='format',
        ),
        migrations.AddField(
            model_name='support',
            name='format',
            field=models.CharField(blank=True, choices=[('4x3', '4m × 3m (12m²) — Standard'), ('4x5', '4m × 5m (20m²) — Standard'), ('7x3', '7m × 3m (21m²) — Standard'), ('10x4', '10m × 4m (40m²) — Géant'), ('12x4', '12m × 4m (48m²) — Géant'), ('12x5', '12m × 5m (60m²) — Géant'), ('24x4', '24m × 4m (96m²) — Géant'), ('9x5', '9m × 5m (45m²) — Géant'), ('1x2', '1,20m × 1,80m (2,16m²) — Sucette'), ('gm-4x3', '4m × 3m (12m²) — Grand Marché'), ('gm-4x4', '4m × 4m (16m²) — Grand Marché'), ('gm-5x4', '5m × 4m (20m²) — Grand Marché'), ('gm-12x3', '12m × 3m (36m²) — Grand Marché'), ('custom', 'Personnalisé (voir notes)')], default='', help_text='Renseigner uniquement pour les panneaux. Commun aux deux faces.', max_length=20, verbose_name='Format & Type'),
        ),
    ]
