# Generated by Django 5.2.13 on 2026-05-25 18:52

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_facepanneau_format_support_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='etat',
            field=models.CharField(choices=[('bon', 'Bon état'), ('panne', 'En panne')], default='bon', max_length=20),
        ),
        migrations.AlterField(
            model_name='support',
            name='format',
            field=models.CharField(blank=True, choices=[('4x3', '4m × 3m (12m²) — Standard'), ('4x5', '4m × 5m (20m²) — Standard'), ('7x3', '7m × 3m (21m²) — Standard'), ('6x4', '6m × 4m (24m²) — Géant'), ('8x4', '8m × 4m (32m²) — Géant'), ('10x4', '10m × 4m (40m²) — Géant'), ('12x4', '12m × 4m (48m²) — Géant'), ('12x5', '12m × 5m (60m²) — Géant'), ('24x4', '24m × 4m (96m²) — Géant'), ('9x5', '9m × 5m (45m²) — Géant'), ('1x2', '1,20m × 1,80m (2,16m²) — Sucette'), ('gm-4x3', '4m × 3m (12m²) — Grand Marché'), ('gm-4x4', '4m × 4m (16m²) — Grand Marché'), ('gm-5x4', '5m × 4m (20m²) — Grand Marché'), ('gm-12x3', '12m × 3m (36m²) — Grand Marché'), ('custom', 'Personnalisé (voir notes)')], default='', help_text='Renseigner uniquement pour les panneaux. Commun aux deux faces.', max_length=20, verbose_name='Format & Type'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'intervention")),
                ('etat_apres', models.CharField(choices=[('bon', 'Bon état'), ('panne', 'En panne')], max_length=20, verbose_name='État enregistré')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=inventory.models.maintenance_photo_upload_path, verbose_name='Photo')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='inventory.support', verbose_name='Support')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date_intervention'],
            },
        ),
        migrations.DeleteModel(
            name='PhotoMaintenance',
        ),
    ]
