# Generated by Django 5.2.13 on 2026-06-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_support_actif_alter_support_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facepanneau',
            name='etat',
            field=models.CharField(choices=[('bon', 'Bon état'), ('maintenance', 'En maintenance'), ('panne', 'En panne')], default='bon', max_length=20, verbose_name='État de la face'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='face',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances_par_face', to='inventory.facepanneau', verbose_name='Face (Panneau)'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='etat_apres',
            field=models.CharField(choices=[('bon', 'Bon état'), ('maintenance', 'En maintenance'), ('panne', 'En panne')], max_length=20, verbose_name='État enregistré'),
        ),
        migrations.AlterField(
            model_name='support',
            name='etat',
            field=models.CharField(choices=[('bon', 'Bon état'), ('maintenance', 'En maintenance'), ('panne', 'En panne')], default='bon', max_length=20),
        ),
    ]
