# Generated by Django 5.2.15 on 2026-06-22 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_facepanneau_etat_maintenance_face_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
