# Generated by Django 5.2.15 on 2026-07-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_support_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code Format (ex: 4x3, gm-5x4)')),
                ('libelle', models.CharField(max_length=150, verbose_name='Description complète')),
                ('dimensions', models.CharField(blank=True, max_length=50, verbose_name='Dimensions (ex: 4m × 3m)')),
                ('superficie', models.FloatField(blank=True, null=True, verbose_name='Superficie en m²')),
                ('categorie', models.CharField(blank=True, max_length=50, verbose_name='Catégorie (Standard, Géant, Sucette, Marché)')),
            ],
            options={
                'verbose_name': 'Format de Support',
                'verbose_name_plural': 'Formats de Supports',
                'ordering': ['categorie', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='support',
            name='format',
            field=models.CharField(blank=True, choices=[('4x3', '4m × 3m (12m²) — Standard'), ('4x5', '4m × 5m (20m²) — Géant'), ('7x3', '7m × 3m (21m²) — Géant'), ('6x4', '6m × 4m (24m²) — Géant'), ('8x3', '8m × 3m (24m²) — Géant'), ('8x6', '8m × 6m (48m²) — Géant'), ('6x8', '6m × 8m (48m²) — Géant'), ('10x4', '10m × 4m (40m²) — Géant'), ('12x4', '12m × 4m (48m²) — Géant'), ('12x5', '12m × 5m (60m²) — Géant'), ('24x4', '24m × 4m (96m²) — Géant'), ('9x5', '9m × 5m (45m²) — Géant'), ('10x4.14', '10m × 4.14m (41.4m²) — Géant'), ('10x4', '10m × 4m (40m²) — Géant'), ('4.5x5.5', '4.5m × 5.5m (24.75m²) — Géant'), ('1x2', '1,20m × 1,80m (2,16m²) — Sucette'), ('gm-4x3', '4m × 3m (12m²) — Marché'), ('gm-4x4', '4m × 4m (16m²) — Marché'), ('gm-5x4', '5m × 4m (20m²) — Marché'), ('gm-12x3', '12m × 3m (36m²) — Marché'), ('custom', 'Personnalisé (voir notes)')], default='', help_text='Renseigner uniquement pour les panneaux. Commun aux deux faces.', max_length=20, verbose_name='Format & Type'),
        ),
    ]
