# Generated by Django 5.2.15 on 2026-07-04 15:58

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_support_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='format',
            field=models.CharField(blank=True, choices=inventory.models.get_dynamic_format_choices, default='', help_text='Renseigner uniquement pour les panneaux. Commun aux deux faces.', max_length=20, verbose_name='Format & Type'),
        ),
    ]
