# Generated by Django 5.2.15 on 2026-07-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_support_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formatsupport',
            name='libelle',
        ),
    ]
