# Generated by Django 5.2.15 on 2026-07-10 19:50

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_formatsupport_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecrannumerique',
            name='cellule',
            field=models.CharField(choices=inventory.models.get_dynamic_format_choices_ecran, default='6x4', help_text='Nombre de spots simultanés (ex: 6x4 = 24)', max_length=10),
        ),
    ]
