# Generated by Django 5.2.15 on 2026-07-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_ecrannumerique_cellule'),
    ]

    operations = [
        migrations.AddField(
            model_name='facepanneau',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_faces/', verbose_name='Photo de la face'),
        ),
    ]
