# Generated by Django 5.2.15 on 2026-08-20 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_facepanneau_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Ex: 'A-01', 'Allée 3 - Stand 12'", max_length=30, verbose_name='Code / repère')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emplacement',
                'verbose_name_plural': 'Emplacements',
                'ordering': ['marche', 'code'],
            },
        ),
        migrations.AddField(
            model_name='support',
            name='emplacement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_installe', to='inventory.emplacement', verbose_name='Emplacement (marché)'),
        ),
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom du marché')),
                ('ville', models.CharField(blank=True, default='Ouagadougou', max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marches_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marché',
                'verbose_name_plural': 'Marchés',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='emplacement',
            name='marche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplacements', to='inventory.marche', verbose_name='Marché'),
        ),
        migrations.AlterUniqueTogether(
            name='emplacement',
            unique_together={('marche', 'code')},
        ),
    ]
