# Generated by Django 5.2.15 on 2026-08-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_emplacement_support_emplacement_marche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplacement',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='emplacement',
            name='longitude',
        ),
        migrations.AddField(
            model_name='marche',
            name='rayon_metres',
            field=models.PositiveIntegerField(default=100, help_text="Zone approximative occupée par le marché sur la carte. Les emplacements individuels n'ont pas de coordonnées propres : ils sont considérés comme situés dans ce périmètre.", verbose_name='Rayon du périmètre (mètres)'),
        ),
        migrations.AlterField(
            model_name='emplacement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
