# Generated by Django 5.2.13 on 2026-04-23 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Raison sociale / Nom')),
                ('contact_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom du Contact principal')),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la campagne')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('a_venir', 'À venir'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('type_support', models.CharField(choices=[('panneau', 'Panneau'), ('ecran', 'Écran')], default='panneau', max_length=10, verbose_name='Type de support')),
                ('visuel', models.FileField(blank=True, null=True, upload_to='visuels/', verbose_name='Visuel / Affiche (photo ou vidéo)')),
                ('duree_passage', models.PositiveIntegerField(blank=True, choices=[(5, '5 secondes'), (10, '10 secondes'), (15, '15 secondes'), (20, '20 secondes')], help_text="Durée d'affichage du spot sur les écrans", null=True, verbose_name='Durée de passage (secondes)')),
                ('frequence', models.PositiveIntegerField(blank=True, choices=[(60, 'Toutes les 1 min'), (120, 'Toutes les 2 min'), (180, 'Toutes les 3 min'), (240, 'Toutes les 4 min'), (600, 'Toutes les 10 min'), (1200, 'Toutes les 20 min')], help_text='Intervalle entre deux diffusions du spot', null=True, verbose_name='Fréquence de diffusion')),
                ('tranches_horaires', models.CharField(blank=True, help_text='Ex: 08:00-12:00, 14:00-18:00 (séparées par des virgules)', max_length=500, verbose_name='Tranches horaires de diffusion')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campagnes', to='campaigns.client')),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('annuel', 'Contrat Annuel'), ('mensuel', 'Contrat Mensuel'), ('ponctuel', 'Ponctuel')], default='ponctuel', max_length=20)),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('nb_spots', models.PositiveIntegerField(default=0, verbose_name='Nombre de spots')),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='campaigns.client')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='LigneCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_spot_sec', models.PositiveIntegerField(blank=True, choices=[(5, '5 secondes'), (10, '10 secondes'), (15, '15 secondes'), (20, '20 secondes')], default=10, help_text="Durée d'affichage du visuel", null=True, verbose_name='Durée du spot (s)')),
                ('frequence_toutes', models.PositiveIntegerField(blank=True, choices=[(60, 'Toutes les 1 min'), (120, 'Toutes les 2 min'), (180, 'Toutes les 3 min'), (240, 'Toutes les 4 min'), (600, 'Toutes les 10 min'), (1200, 'Toutes les 20 min')], default=120, help_text='Ex: 120 pour une diffusion toutes les 2 minutes', null=True, verbose_name='Fréquence (en secondes)')),
                ('heure_debut_diffusion', models.TimeField(blank=True, null=True, verbose_name='H. Début Diffusion')),
                ('heure_fin_diffusion', models.TimeField(blank=True, null=True, verbose_name='H. Fin Diffusion')),
                ('visuel', models.FileField(blank=True, null=True, upload_to='visuels/', verbose_name='Visuel / Média')),
                ('ordre_dans_boucle', models.PositiveIntegerField(default=0, verbose_name='Priorité/Ordre')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='campaigns.campagne')),
                ('face', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_campagne', to='inventory.facepanneau', verbose_name='Face (Panneau)')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_campagne', to='inventory.support')),
            ],
            options={
                'verbose_name': 'Ligne de Campagne',
                'verbose_name_plural': 'Lignes de Campagne',
                'ordering': ['support__code'],
            },
        ),
    ]
