# Generated by Django 5.2.13 on 2026-04-29 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='contrat',
            field=models.ForeignKey(blank=True, help_text='Contrat associé à cette diffusion sur écran', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes', to='campaigns.contrat'),
        ),
    ]
