# Generated by Django 5.2.13 on 2026-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campagne_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du contrat (optionnel)'),
        ),
    ]
