# Generated by Django 5.2.13 on 2026-05-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_contrat_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignecampagne',
            name='heure_debut_diffusion',
        ),
        migrations.RemoveField(
            model_name='lignecampagne',
            name='heure_fin_diffusion',
        ),
        migrations.AddField(
            model_name='lignecampagne',
            name='tranches_horaires',
            field=models.CharField(blank=True, default='', help_text='Ex: 08:00-12:00, 14:00-18:00 (séparées par des virgules). Doit être égale aux tranches horaires de la campagne.', max_length=500, verbose_name='Tranches horaires spécifiques au spot'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='tranches_horaires',
            field=models.CharField(blank=True, default='08:00-12:00', help_text='Ex: 08:00-12:00, 14:00-18:00 (séparées par des virgules)', max_length=500, verbose_name='Tranches horaires de diffusion'),
        ),
    ]
