# Generated by Django 5.2.13 on 2026-05-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_lignecampagne_heure_debut_diffusion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignecampagne',
            name='duree_spot_sec',
        ),
        migrations.RemoveField(
            model_name='lignecampagne',
            name='frequence_toutes',
        ),
        migrations.RemoveField(
            model_name='lignecampagne',
            name='tranches_horaires',
        ),
    ]
