# Generated by Django 5.2.13 on 2026-05-14 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_remove_lignecampagne_duree_spot_sec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='frequence',
            field=models.PositiveIntegerField(blank=True, choices=[(60, 'Toutes les 1 min'), (120, 'Toutes les 2 min'), (180, 'Toutes les 3 min'), (240, 'Toutes les 4 min'), (300, 'Toutes les 5 min'), (600, 'Toutes les 10 min'), (900, 'Toutes les 15 min'), (1200, 'Toutes les 20 min'), (1800, 'Toutes les 30 min')], default=120, help_text='Intervalle entre deux diffusions du spot', null=True, verbose_name='Fréquence de diffusion'),
        ),
        migrations.CreateModel(
            name='CampagneVisuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='visuels/', verbose_name='Visuel / Affiche (photo ou vidéo)')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visuels', to='campaigns.campagne')),
            ],
            options={
                'verbose_name': 'Visuel de campagne',
                'verbose_name_plural': 'Visuels de campagne',
            },
        ),
    ]
