# Generated by Django 5.2.13 on 2026-05-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campagne_frequence_campagnevisuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagne',
            name='visuel',
        ),
    ]
