# Generated by Django 5.2.13 on 2026-05-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_remove_campagne_visuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
