# Generated by Django 5.2.13 on 2026-05-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campagne_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='archive',
            field=models.BooleanField(default=True),
        ),
    ]
