# Generated by Django 5.2.13 on 2026-06-04 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_contrat_archive'),
        ('inventory', '0005_support_actif_alter_support_etat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationPanneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='campaigns.client')),
                ('face', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_client', to='inventory.facepanneau', verbose_name='Face (Panneau)')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_client', to='inventory.support')),
            ],
        ),
    ]
