# Generated by Django 5.2.15 on 2026-06-23 15:17 (modifié manuellement)

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def add_field_if_not_exists(apps, schema_editor, table, column, sql):
    db = schema_editor.connection
    columns = [col.name for col in db.introspection.get_table_description(db.cursor(), table)]
    if column not in columns:
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_reservationpanneau'),
        ('inventory', '0009_alter_support_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignecampagne',
            options={'verbose_name': 'Ligne de campagne', 'verbose_name_plural': 'Lignes de campagne'},
        ),
        # Colonnes ajoutées manuellement via RunPython pour éviter les doublons
        migrations.RunPython(
            lambda apps, se: add_field_if_not_exists(apps, se, 'campaigns_lignecampagne', 'date_debut',
                'ALTER TABLE campaigns_lignecampagne ADD COLUMN date_debut date NULL'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            lambda apps, se: add_field_if_not_exists(apps, se, 'campaigns_lignecampagne', 'date_fin',
                'ALTER TABLE campaigns_lignecampagne ADD COLUMN date_fin date NULL'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            lambda apps, se: add_field_if_not_exists(apps, se, 'campaigns_lignecampagne', 'duree_passage',
                'ALTER TABLE campaigns_lignecampagne ADD COLUMN duree_passage integer NULL'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            lambda apps, se: add_field_if_not_exists(apps, se, 'campaigns_lignecampagne', 'frequence',
                'ALTER TABLE campaigns_lignecampagne ADD COLUMN frequence integer NULL'),
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            lambda apps, se: add_field_if_not_exists(apps, se, 'campaigns_lignecampagne', 'tranches_horaires',
                "ALTER TABLE campaigns_lignecampagne ADD COLUMN tranches_horaires varchar(500) NOT NULL DEFAULT ''"),
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='campagne',
            name='contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes', to='campaigns.contrat'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='duree_passage',
            field=models.PositiveIntegerField(blank=True, choices=[(5, '5 secondes'), (10, '10 secondes'), (15, '15 secondes'), (20, '20 secondes')], null=True, verbose_name='Durée de passage (secondes)'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='frequence',
            field=models.PositiveIntegerField(blank=True, choices=[(60, 'Toutes les 1 min'), (120, 'Toutes les 2 min'), (180, 'Toutes les 3 min'), (240, 'Toutes les 4 min'), (300, 'Toutes les 5 min'), (600, 'Toutes les 10 min'), (900, 'Toutes les 15 min'), (1200, 'Toutes les 20 min'), (1800, 'Toutes les 30 min')], default=120, null=True, verbose_name='Fréquence de diffusion'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='tranches_horaires',
            field=models.CharField(blank=True, default='08:00-12:00', max_length=500, verbose_name='Tranches horaires de diffusion'),
        ),
        migrations.AlterField(
            model_name='reservationpanneau',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_panneaux', to='campaigns.client'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Identifiant public (UUID)')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la réservation')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('expiree', 'Expirée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_globales', to='campaigns.client', verbose_name='Client')),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='campaigns.contrat', verbose_name='Contrat associé (optionnel)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ReservationLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('face', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_reservation', to='inventory.facepanneau', verbose_name='Face')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='campaigns.reservation', verbose_name='Réservation')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_reservation', to='inventory.support', verbose_name='Support')),
            ],
            options={
                'verbose_name': 'Ligne de réservation',
                'verbose_name_plural': 'Lignes de réservation',
                'ordering': ['support__code', 'face__label'],
                'unique_together': {('reservation', 'face')},
            },
        ),
    ]