# Generated by Django 5.2.13 on 2026-06-04 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_alter_reservationpanneau_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationpanneau',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='campaigns.client'),
        ),
    ]
