# Generated by Django 5.2.15 on 2026-06-26 09:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_alter_lignecampagne_options_lignecampagne_date_debut_and_more'),
        ('inventory', '0009_alter_support_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecampagne',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début (écran)'),
        ),
        migrations.AddField(
            model_name='lignecampagne',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin (écran)'),
        ),
        migrations.AddField(
            model_name='lignecampagne',
            name='duree_passage',
            field=models.PositiveIntegerField(blank=True, choices=[(5, '5 secondes'), (10, '10 secondes'), (15, '15 secondes'), (20, '20 secondes')], null=True, verbose_name='Durée de passage (secondes)'),
        ),
        migrations.AddField(
            model_name='lignecampagne',
            name='frequence',
            field=models.PositiveIntegerField(blank=True, choices=[(60, 'Toutes les 1 min'), (120, 'Toutes les 2 min'), (180, 'Toutes les 3 min'), (240, 'Toutes les 4 min'), (300, 'Toutes les 5 min'), (600, 'Toutes les 10 min'), (900, 'Toutes les 15 min'), (1200, 'Toutes les 20 min'), (1800, 'Toutes les 30 min')], null=True, verbose_name='Fréquence de diffusion'),
        ),
        migrations.AddField(
            model_name='lignecampagne',
            name='tranches_horaires',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tranches horaires spécifiques'),
        ),
        migrations.CreateModel(
            name='DemandeReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Identifiant public')),
                ('reference', models.CharField(blank=True, help_text='Générée automatiquement. Ex: DEM-2026-A3F9K2', max_length=50, unique=True, verbose_name='Référence')),
                ('nom_contact', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('societe', models.CharField(blank=True, max_length=200, verbose_name='Société / Organisation')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('accepte_contact', models.BooleanField(default=False, help_text="Le visiteur a coché la case d'acceptation de contact commercial.", verbose_name="Accepte d'être recontacté")),
                ('date_debut_souhaitee', models.DateField(verbose_name='Date de début souhaitée')),
                ('date_fin_souhaitee', models.DateField(verbose_name='Date de fin souhaitée')),
                ('nom_campagne', models.CharField(blank=True, max_length=200, verbose_name='Nom de la campagne / projet')),
                ('message', models.TextField(blank=True, verbose_name='Message libre')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours de traitement'), ('validee', 'Validée — Réservation créée'), ('refusee', 'Refusée')], db_index=True, default='nouvelle', max_length=20, verbose_name='Statut')),
                ('notes_staff', models.TextField(blank=True, help_text='Visible uniquement par le staff. Motif de refus, remarques…', verbose_name='Notes internes staff')),
                ('traite_le', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('client', models.ForeignKey(blank=True, help_text='Renseigné par le staff après validation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_reservation', to='campaigns.client', verbose_name='Client associé')),
                ('faces_souhaitees', models.ManyToManyField(blank=True, related_name='demandes_reservation', to='inventory.facepanneau', verbose_name='Faces souhaitées')),
                ('reservation', models.ForeignKey(blank=True, help_text='Réservation officielle créée par le staff après validation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine', to='campaigns.reservation', verbose_name='Réservation créée')),
                ('supports_souhaites', models.ManyToManyField(blank=True, related_name='demandes_reservation', to='inventory.support', verbose_name='Supports souhaités (écrans)')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Demande de réservation',
                'verbose_name_plural': 'Demandes de réservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ReservationPanneau',
        ),
        migrations.AddIndex(
            model_name='demandereservation',
            index=models.Index(fields=['statut', '-created_at'], name='campaigns_d_statut_52ee43_idx'),
        ),
        migrations.AddIndex(
            model_name='demandereservation',
            index=models.Index(fields=['email'], name='campaigns_d_email_12c102_idx'),
        ),
    ]
