# Generated by Django 5.2.15 on 2026-07-02 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_lignecampagne_date_debut_lignecampagne_date_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='campagne_parente',
            field=models.ForeignKey(blank=True, help_text='Si renseigné, cette campagne est une sous-campagne rattachée à une campagne mère. Laissez vide pour une campagne autonome.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_campagnes', to='campaigns.campagne', verbose_name='Campagne mère'),
        ),
        migrations.AddField(
            model_name='campagne',
            name='format_cible',
            field=models.CharField(blank=True, help_text='Format ciblé pour une sous-campagne panneau ; laisser vide pour les écrans.', max_length=20, verbose_name='Format ciblé'),
        ),
    ]
