# Generated by Django 5.2.15 on 2026-07-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_campagne_campagne_parente_campagne_format_cible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagne',
            name='format_cible',
        ),
        migrations.AddField(
            model_name='campagne',
            name='est_mere',
            field=models.BooleanField(default=False, verbose_name='Campagne mère'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='type_support',
            field=models.CharField(blank=True, default='', help_text='Écran ou format de panneau (ex: 4x3, 1x2, gm-5x4).', max_length=20, verbose_name='Type de support'),
        ),
    ]
