# Generated by Django 5.2.15 on 2026-07-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_remove_campagne_format_cible_campagne_est_mere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='type_support',
            field=models.CharField(blank=True, choices=[('ecran', 'Écran'), ('4x3', '4m × 3m (12m²) — 12m²'), ('10x4', '10m × 4m (40m²14) — Géant'), ('10x4.14', '10m × 4.14m (41.4m²) — Géant'), ('12x4', '12m × 4m (48m²) — Géant'), ('12x5', '12m × 5m (60m²) — Géant'), ('24x4', '24m × 4m (96m²) — Géant'), ('4.5x5.5', '4.5m × 5.5m (24.75m²) — Géant'), ('4x5', '4m × 5m (20m²) — Géant'), ('6x4', '6m × 4m (24m²) — Géant'), ('6x8', '6m × 8m (48m²) — Géant'), ('7x3', '7m × 3m (21m²) — Géant'), ('8x3', '8m × 3m (24m²) — Géant'), ('8x6', '8m × 6m (48m²) — Géant'), ('9x5', '9m × 5m (45m²) — Géant'), ('gm-12x3', '12m × 3m (36m²) — Marché'), ('gm-4x3', '4m × 3m (12m²) — Marché'), ('gm-4x4', '4m × 4m (16m²) — Marché'), ('gm-5x4', '5m × 4m (20m²) — Marché'), ('custom', 'Personnalisé (voir notes)'), ('1x2', '1,20m × 1,80m (2,16m²) — Sucette')], default='', help_text='Écran ou format de panneau (ex: 4x3, 1x2, gm-5x4).', max_length=20, verbose_name='Type de support'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=30),
        ),
    ]
