# Generated by Django 5.2.15 on 2026-07-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_alter_campagne_type_support_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix'),
        ),
    ]
