# Generated by Django 5.2.15 on 2026-07-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_campagne_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='prix_affichage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire affichage'),
        ),
        migrations.AddField(
            model_name='campagne',
            name='prix_impression',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire impression'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire face'),
        ),
    ]
