# Generated by Django 5.2.15 on 2026-07-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_campagne_prix_affichage_campagne_prix_impression_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire face'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='prix_affichage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire affichage'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='prix_impression',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire impression'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='statut',
            field=models.CharField(blank=True, choices=[('brouillon', 'Brouillon'), ('a_venir', 'À venir'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_cours', max_length=20),
        ),
    ]
