# Generated by Django 5.2.15 on 2026-07-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_alter_campagne_prix_alter_campagne_prix_affichage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='lieu',
            field=models.CharField(blank=True, help_text='Ville ou zone géographique de la campagne.', max_length=200, verbose_name='Lieu de la campagne'),
        ),
    ]
