# Generated by Django 5.2.15 on 2026-07-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_alter_campagne_type_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='type_support',
            field=models.CharField(blank=True, choices=[('ecran', 'Écran'), ('4x3', '4m × 3m (12.0m²)'), ('10x4', '10m × 4m (40.0m²)'), ('10x4.14', '10m × 4.14m (41.4m²)'), ('12x4', '12m × 4m (48.0m²)'), ('12x5', '12m × 5m (60.0m²)'), ('24x4', '24m × 4m (96.0m²)'), ('4.5x5.5', '4.5m × 5.5m (24.75m²)'), ('4x5', '4m × 5m (20.0m²)'), ('6x4', '6m × 4m (24.0m²)'), ('6x8', '6m × 8m (48.0m²)'), ('7x3', '7m × 3m (21.0m²)'), ('8x3', '8m × 3m (24.0m²)'), ('8x6', '8m × 6m (48.0m²)'), ('9x5', '9m × 5m (45.0m²)'), ('gm-12x3', '12m × 3m (36.0m²)'), ('gm-4x3', '4m × 3m (12.0m²)'), ('gm-4x4', '4m × 4m (16.0m²)'), ('gm-5x4', '5m × 4m (20.0m²)'), ('custom', 'Personnalisé'), ('1x2', '1.20m × 1.80m (2.16m²)')], default='', help_text='Écran ou format de panneau (ex: 4x3, 1x2, gm-5x4).', max_length=20, verbose_name='Type de support'),
        ),
    ]
