# Generated by Django 5.2.15 on 2026-07-04 16:51

import campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_alter_campagne_type_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='type_support',
            field=models.CharField(blank=True, choices=campaigns.models.get_type_support_choices, default='', help_text='Écran ou format de panneau (ex: 4x3, 1x2, gm-5x4).', max_length=20, verbose_name='Type de support'),
        ),
    ]
