# Generated by Django 5.2.15 on 2026-07-10 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_alter_campagne_type_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reference',
            field=models.CharField(blank=True, editable=False, help_text="Généré automatiquement. Ex: CLI-00001. À communiquer au client pour qu'il puisse s'identifier lors d'une future demande.", max_length=20, verbose_name='Code client'),
        ),
        migrations.AddField(
            model_name='demandereservation',
            name='reference_client_saisie',
            field=models.CharField(blank=True, help_text="Code client (ex: CLI-2026-A3F9K2) fourni par le visiteur s'il se déclare déjà client. Rempli côté public, vérifié par le staff.", max_length=20, verbose_name='Référence client saisie'),
        ),
        migrations.AddField(
            model_name='demandereservation',
            name='type_client',
            field=models.CharField(choices=[('nouveau', 'Nouveau client'), ('existant', 'Client existant')], default='nouveau', max_length=10, verbose_name='Type de client'),
        ),
        migrations.AlterField(
            model_name='demandereservation',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Renseigné automatiquement si la référence client saisie est valide, sinon par le staff après validation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_reservation', to='campaigns.client', verbose_name='Client associé'),
        ),
    ]
