# Generated by Django 5.2.15 on 2026-07-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0023_client_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='reference',
            field=models.CharField(blank=True, editable=False, help_text="Généré automatiquement. Ex: CLI-00001. À communiquer au client pour qu'il puisse s'identifier lors d'une future demande.", max_length=20, unique=True, verbose_name='Code client'),
        ),
    ]
