# Generated by Django 5.2.15 on 2026-08-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0024_alter_client_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='nombre_visuels',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de visuels diffusés dans la boucle. Par défaut : 1.', verbose_name='Nombre de visuels'),
        ),
    ]
