# Generated by Django 5.2.15 on 2026-08-22 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0025_campagne_nombre_visuels'),
        ('inventory', '0017_remove_emplacement_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecampagne',
            name='emplacement',
            field=models.ForeignKey(blank=True, help_text="Renseigné uniquement pour les campagnes de type Marché — l'emplacement peut être réservé même s'il n'a pas encore de panneau installé.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_campagne', to='inventory.emplacement', verbose_name='Emplacement (Marché)'),
        ),
        migrations.AlterField(
            model_name='lignecampagne',
            name='support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_campagne', to='inventory.support'),
        ),
    ]
